name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  labeler:
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
